# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'drone_app.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WaterSamplingGroundControlStation(object):
    def setupUi(self, WaterSamplingGroundControlStation):
        WaterSamplingGroundControlStation.setObjectName("WaterSamplingGroundControlStation")
        WaterSamplingGroundControlStation.resize(1341, 857)
        self.Initialization_Tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Initialization_Tab.setFont(font)
        self.Initialization_Tab.setObjectName("Initialization_Tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Initialization_Tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 941, 761))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.InitVLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.InitVLayout.setContentsMargins(0, 0, 0, 0)
        self.InitVLayout.setObjectName("InitVLayout")
        self.InitTitle = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.InitTitle.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.InitTitle.setFont(font)
        self.InitTitle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.InitTitle.setObjectName("InitTitle")
        self.InitVLayout.addWidget(self.InitTitle)
        self.Welcome = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Welcome.setWordWrap(True)
        self.Welcome.setObjectName("Welcome")
        self.InitVLayout.addWidget(self.Welcome)
        self.ROSCoreInfo = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.ROSCoreInfo.setWordWrap(True)
        self.ROSCoreInfo.setObjectName("ROSCoreInfo")
        self.InitVLayout.addWidget(self.ROSCoreInfo)
        self.StartROSCore = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.StartROSCore.setObjectName("StartROSCore")
        self.InitVLayout.addWidget(self.StartROSCore)
        self.MAVROSInfo = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.MAVROSInfo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.MAVROSInfo.setWordWrap(True)
        self.MAVROSInfo.setObjectName("MAVROSInfo")
        self.InitVLayout.addWidget(self.MAVROSInfo)
        self.StartMAVROS = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.StartMAVROS.setObjectName("StartMAVROS")
        self.InitVLayout.addWidget(self.StartMAVROS)
        self.OFFBOARDInfo = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.OFFBOARDInfo.setWordWrap(True)
        self.OFFBOARDInfo.setObjectName("OFFBOARDInfo")
        self.InitVLayout.addWidget(self.OFFBOARDInfo)
        self.StartOffboard = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.StartOffboard.setObjectName("StartOffboard")
        self.InitVLayout.addWidget(self.StartOffboard)
        WaterSamplingGroundControlStation.addTab(self.Initialization_Tab, "")
        self.AutonomousFlightMode_Tab = QtWidgets.QWidget()
        self.AutonomousFlightMode_Tab.setObjectName("AutonomousFlightMode_Tab")
        self.AutonomousTitle = QtWidgets.QLabel(self.AutonomousFlightMode_Tab)
        self.AutonomousTitle.setGeometry(QtCore.QRect(30, 15, 481, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.AutonomousTitle.setFont(font)
        self.AutonomousTitle.setObjectName("AutonomousTitle")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 80, 301, 181))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.GPSDataLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.GPSDataLayout.setContentsMargins(0, 0, 0, 0)
        self.GPSDataLayout.setObjectName("GPSDataLayout")
        self.GPSLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.GPSLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.GPSLabel.setObjectName("GPSLabel")
        self.GPSDataLayout.addWidget(self.GPSLabel)
        self.GPSHLayout = QtWidgets.QHBoxLayout()
        self.GPSHLayout.setObjectName("GPSHLayout")
        self.LatLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.LatLabel.setObjectName("LatLabel")
        self.GPSHLayout.addWidget(self.LatLabel)
        self.LongLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.LongLabel.setObjectName("LongLabel")
        self.GPSHLayout.addWidget(self.LongLabel)
        self.AltLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.AltLabel.setObjectName("AltLabel")
        self.GPSHLayout.addWidget(self.AltLabel)
        self.GPSDataLayout.addLayout(self.GPSHLayout)
        self.GPS_DISP = QtWidgets.QHBoxLayout()
        self.GPS_DISP.setObjectName("GPS_DISP")
        self.LatGPS_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_2)
        self.LatGPS_DISP.setObjectName("LatGPS_DISP")
        self.GPS_DISP.addWidget(self.LatGPS_DISP)
        self.LongGPS_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_2)
        self.LongGPS_DISP.setObjectName("LongGPS_DISP")
        self.GPS_DISP.addWidget(self.LongGPS_DISP)
        self.AltGPS_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_2)
        self.AltGPS_DISP.setObjectName("AltGPS_DISP")
        self.GPS_DISP.addWidget(self.AltGPS_DISP)
        self.GPSDataLayout.addLayout(self.GPS_DISP)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(350, 270, 291, 191))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.IMULayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.IMULayout.setContentsMargins(0, 0, 0, 0)
        self.IMULayout.setObjectName("IMULayout")
        self.IMULabel = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.IMULabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.IMULabel.setObjectName("IMULabel")
        self.IMULayout.addWidget(self.IMULabel)
        self.IMUHLayout = QtWidgets.QHBoxLayout()
        self.IMUHLayout.setObjectName("IMUHLayout")
        self.XLabel0 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.XLabel0.setObjectName("XLabel0")
        self.IMUHLayout.addWidget(self.XLabel0)
        self.YLabel0 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.YLabel0.setObjectName("YLabel0")
        self.IMUHLayout.addWidget(self.YLabel0)
        self.ZLabel0 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.ZLabel0.setObjectName("ZLabel0")
        self.IMUHLayout.addWidget(self.ZLabel0)
        self.IMULayout.addLayout(self.IMUHLayout)
        self.IMU_DISP = QtWidgets.QHBoxLayout()
        self.IMU_DISP.setObjectName("IMU_DISP")
        self.X_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_4)
        self.X_DISP.setObjectName("X_DISP")
        self.IMU_DISP.addWidget(self.X_DISP)
        self.Y_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_4)
        self.Y_DISP.setObjectName("Y_DISP")
        self.IMU_DISP.addWidget(self.Y_DISP)
        self.Z_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_4)
        self.Z_DISP.setDigitCount(6)
        self.Z_DISP.setObjectName("Z_DISP")
        self.IMU_DISP.addWidget(self.Z_DISP)
        self.IMULayout.addLayout(self.IMU_DISP)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(30, 270, 301, 191))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.VelVLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.VelVLayout.setContentsMargins(0, 0, 0, 0)
        self.VelVLayout.setObjectName("VelVLayout")
        self.VelLabel = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.VelLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.VelLabel.setObjectName("VelLabel")
        self.VelVLayout.addWidget(self.VelLabel)
        self.VelHLabel = QtWidgets.QHBoxLayout()
        self.VelHLabel.setObjectName("VelHLabel")
        self.U_VEL_Label = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.U_VEL_Label.setObjectName("U_VEL_Label")
        self.VelHLabel.addWidget(self.U_VEL_Label)
        self.V_VEL_Label = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.V_VEL_Label.setObjectName("V_VEL_Label")
        self.VelHLabel.addWidget(self.V_VEL_Label)
        self.W_VEL_Label = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.W_VEL_Label.setObjectName("W_VEL_Label")
        self.VelHLabel.addWidget(self.W_VEL_Label)
        self.VelVLayout.addLayout(self.VelHLabel)
        self.Vel_DISP = QtWidgets.QHBoxLayout()
        self.Vel_DISP.setObjectName("Vel_DISP")
        self.U_Vel_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_5)
        self.U_Vel_DISP.setObjectName("U_Vel_DISP")
        self.Vel_DISP.addWidget(self.U_Vel_DISP)
        self.V_Vel_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_5)
        self.V_Vel_DISP.setObjectName("V_Vel_DISP")
        self.Vel_DISP.addWidget(self.V_Vel_DISP)
        self.W_Vel_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_5)
        self.W_Vel_DISP.setObjectName("W_Vel_DISP")
        self.Vel_DISP.addWidget(self.W_Vel_DISP)
        self.VelVLayout.addLayout(self.Vel_DISP)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(660, 170, 161, 91))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.FlightTimeVLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.FlightTimeVLayout.setContentsMargins(0, 0, 0, 0)
        self.FlightTimeVLayout.setObjectName("FlightTimeVLayout")
        self.FlightTimeLabel = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.FlightTimeLabel.setObjectName("FlightTimeLabel")
        self.FlightTimeVLayout.addWidget(self.FlightTimeLabel)
        self.FlightTimeHLabel = QtWidgets.QHBoxLayout()
        self.FlightTimeHLabel.setObjectName("FlightTimeHLabel")
        self.Min_Label = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.Min_Label.setObjectName("Min_Label")
        self.FlightTimeHLabel.addWidget(self.Min_Label)
        self.Sec_Label = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.Sec_Label.setObjectName("Sec_Label")
        self.FlightTimeHLabel.addWidget(self.Sec_Label)
        self.FlightTimeVLayout.addLayout(self.FlightTimeHLabel)
        self.FlightTime_DISP = QtWidgets.QHBoxLayout()
        self.FlightTime_DISP.setObjectName("FlightTime_DISP")
        self.Min_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_6)
        self.Min_DISP.setObjectName("Min_DISP")
        self.FlightTime_DISP.addWidget(self.Min_DISP)
        self.Sec_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_6)
        self.Sec_DISP.setObjectName("Sec_DISP")
        self.FlightTime_DISP.addWidget(self.Sec_DISP)
        self.FlightTimeVLayout.addLayout(self.FlightTime_DISP)
        self.Logging = QtWidgets.QTextBrowser(self.AutonomousFlightMode_Tab)
        self.Logging.setGeometry(QtCore.QRect(1040, 80, 291, 381))
        self.Logging.setObjectName("Logging")
        self.FlightLogTitle = QtWidgets.QLabel(self.AutonomousFlightMode_Tab)
        self.FlightLogTitle.setGeometry(QtCore.QRect(1080, 20, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.FlightLogTitle.setFont(font)
        self.FlightLogTitle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.FlightLogTitle.setObjectName("FlightLogTitle")
        self.EmergencyStop = QtWidgets.QPushButton(self.AutonomousFlightMode_Tab)
        self.EmergencyStop.setEnabled(True)
        self.EmergencyStop.setGeometry(QtCore.QRect(660, 270, 161, 71))
        self.EmergencyStop.setObjectName("EmergencyStop")
        self.verticalLayoutWidget_14 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(350, 80, 291, 181))
        self.verticalLayoutWidget_14.setObjectName("verticalLayoutWidget_14")
        self.GPSDataLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_14)
        self.GPSDataLayout_3.setContentsMargins(0, 0, 0, 0)
        self.GPSDataLayout_3.setObjectName("GPSDataLayout_3")
        self.GPSLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.GPSLabel_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.GPSLabel_2.setObjectName("GPSLabel_2")
        self.GPSDataLayout_3.addWidget(self.GPSLabel_2)
        self.GPSHLayout_2 = QtWidgets.QHBoxLayout()
        self.GPSHLayout_2.setObjectName("GPSHLayout_2")
        self.LatLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.LatLabel_2.setObjectName("LatLabel_2")
        self.GPSHLayout_2.addWidget(self.LatLabel_2)
        self.LongLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.LongLabel_2.setObjectName("LongLabel_2")
        self.GPSHLayout_2.addWidget(self.LongLabel_2)
        self.AltLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.AltLabel_2.setObjectName("AltLabel_2")
        self.GPSHLayout_2.addWidget(self.AltLabel_2)
        self.GPSDataLayout_3.addLayout(self.GPSHLayout_2)
        self.GPS_DISP_2 = QtWidgets.QHBoxLayout()
        self.GPS_DISP_2.setObjectName("GPS_DISP_2")
        self.RelX_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_14)
        self.RelX_DISP.setObjectName("RelX_DISP")
        self.GPS_DISP_2.addWidget(self.RelX_DISP)
        self.RelY_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_14)
        self.RelY_DISP.setObjectName("RelY_DISP")
        self.GPS_DISP_2.addWidget(self.RelY_DISP)
        self.AGL_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_14)
        self.AGL_DISP.setObjectName("AGL_DISP")
        self.GPS_DISP_2.addWidget(self.AGL_DISP)
        self.GPSDataLayout_3.addLayout(self.GPS_DISP_2)
        self.gridLayoutWidget = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(660, 80, 161, 77))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.BatLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.BatLayout.setContentsMargins(0, 0, 0, 0)
        self.BatLayout.setObjectName("BatLayout")
        self.BatInd = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.BatInd.setProperty("value", 20)
        self.BatInd.setTextVisible(False)
        self.BatInd.setObjectName("BatInd")
        self.BatLayout.addWidget(self.BatInd, 1, 0, 1, 2)
        self.Voltage_Label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Voltage_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Voltage_Label.setObjectName("Voltage_Label")
        self.BatLayout.addWidget(self.Voltage_Label, 0, 0, 1, 1)
        self.VOLT_DISP = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.VOLT_DISP.setObjectName("VOLT_DISP")
        self.BatLayout.addWidget(self.VOLT_DISP, 0, 1, 1, 1)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(840, 80, 181, 261))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.StateConnected = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.StateConnected.setStyleSheet("color : red")
        self.StateConnected.setFrameShape(QtWidgets.QFrame.Box)
        self.StateConnected.setFrameShadow(QtWidgets.QFrame.Plain)
        self.StateConnected.setAlignment(QtCore.Qt.AlignCenter)
        self.StateConnected.setObjectName("StateConnected")
        self.verticalLayout.addWidget(self.StateConnected)
        self.StateARM = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.StateARM.setStyleSheet("color : green")
        self.StateARM.setFrameShape(QtWidgets.QFrame.Box)
        self.StateARM.setFrameShadow(QtWidgets.QFrame.Plain)
        self.StateARM.setAlignment(QtCore.Qt.AlignCenter)
        self.StateARM.setObjectName("StateARM")
        self.verticalLayout.addWidget(self.StateARM)
        self.StateMode = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.StateMode.setStyleSheet("")
        self.StateMode.setFrameShape(QtWidgets.QFrame.Box)
        self.StateMode.setFrameShadow(QtWidgets.QFrame.Plain)
        self.StateMode.setAlignment(QtCore.Qt.AlignCenter)
        self.StateMode.setObjectName("StateMode")
        self.verticalLayout.addWidget(self.StateMode)
        self.StateVRS = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.StateVRS.setStyleSheet("color : blue")
        self.StateVRS.setFrameShape(QtWidgets.QFrame.Box)
        self.StateVRS.setFrameShadow(QtWidgets.QFrame.Plain)
        self.StateVRS.setAlignment(QtCore.Qt.AlignCenter)
        self.StateVRS.setObjectName("StateVRS")
        self.verticalLayout.addWidget(self.StateVRS)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.gridLayoutWidget_2.setEnabled(True)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 550, 301, 241))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.DISARM = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.DISARM.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DISARM.sizePolicy().hasHeightForWidth())
        self.DISARM.setSizePolicy(sizePolicy)
        self.DISARM.setObjectName("DISARM")
        self.gridLayout.addWidget(self.DISARM, 1, 1, 1, 1)
        self.Land = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.Land.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Land.sizePolicy().hasHeightForWidth())
        self.Land.setSizePolicy(sizePolicy)
        self.Land.setObjectName("Land")
        self.gridLayout.addWidget(self.Land, 4, 0, 1, 2)
        self.ARM = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ARM.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ARM.sizePolicy().hasHeightForWidth())
        self.ARM.setSizePolicy(sizePolicy)
        self.ARM.setObjectName("ARM")
        self.gridLayout.addWidget(self.ARM, 1, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(350, 550, 201, 241))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.HOLD = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HOLD.sizePolicy().hasHeightForWidth())
        self.HOLD.setSizePolicy(sizePolicy)
        self.HOLD.setIconSize(QtCore.QSize(16, 16))
        self.HOLD.setCheckable(False)
        self.HOLD.setAutoDefault(False)
        self.HOLD.setDefault(False)
        self.HOLD.setFlat(False)
        self.HOLD.setObjectName("HOLD")
        self.gridLayout_3.addWidget(self.HOLD, 4, 1, 1, 1)
        self.OFFBOARD = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.OFFBOARD.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OFFBOARD.sizePolicy().hasHeightForWidth())
        self.OFFBOARD.setSizePolicy(sizePolicy)
        self.OFFBOARD.setObjectName("OFFBOARD")
        self.gridLayout_3.addWidget(self.OFFBOARD, 0, 1, 1, 1)
        self.RESET_ORIGIN = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.RESET_ORIGIN.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RESET_ORIGIN.sizePolicy().hasHeightForWidth())
        self.RESET_ORIGIN.setSizePolicy(sizePolicy)
        self.RESET_ORIGIN.setObjectName("RESET_ORIGIN")
        self.gridLayout_3.addWidget(self.RESET_ORIGIN, 5, 1, 1, 1)
        self.AutonomousTitle_3 = QtWidgets.QLabel(self.AutonomousFlightMode_Tab)
        self.AutonomousTitle_3.setGeometry(QtCore.QRect(30, 484, 551, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.AutonomousTitle_3.setFont(font)
        self.AutonomousTitle_3.setObjectName("AutonomousTitle_3")
        self.SendPositionUAV = QtWidgets.QPushButton(self.AutonomousFlightMode_Tab)
        self.SendPositionUAV.setGeometry(QtCore.QRect(1130, 760, 201, 31))
        self.SendPositionUAV.setObjectName("SendPositionUAV")
        self.GetCurrentPositionUAV = QtWidgets.QPushButton(self.AutonomousFlightMode_Tab)
        self.GetCurrentPositionUAV.setGeometry(QtCore.QRect(910, 760, 201, 31))
        self.GetCurrentPositionUAV.setObjectName("GetCurrentPositionUAV")
        self.verticalLayoutWidget_15 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.verticalLayoutWidget_15.setGeometry(QtCore.QRect(910, 550, 421, 201))
        self.verticalLayoutWidget_15.setObjectName("verticalLayoutWidget_15")
        self.DesiredFlightLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_15)
        self.DesiredFlightLayout.setContentsMargins(0, 0, 0, 0)
        self.DesiredFlightLayout.setObjectName("DesiredFlightLayout")
        self.DesiredFlightCoordinates = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.DesiredFlightCoordinates.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.DesiredFlightCoordinates.setObjectName("DesiredFlightCoordinates")
        self.DesiredFlightLayout.addWidget(self.DesiredFlightCoordinates)
        self.FlightHLayout = QtWidgets.QHBoxLayout()
        self.FlightHLayout.setObjectName("FlightHLayout")
        self.XLabel1 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.XLabel1.setObjectName("XLabel1")
        self.FlightHLayout.addWidget(self.XLabel1)
        self.YLabel1 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.YLabel1.setObjectName("YLabel1")
        self.FlightHLayout.addWidget(self.YLabel1)
        self.ZLabel1 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.ZLabel1.setObjectName("ZLabel1")
        self.FlightHLayout.addWidget(self.ZLabel1)
        self.ZLabel1_3 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.ZLabel1_3.setObjectName("ZLabel1_3")
        self.FlightHLayout.addWidget(self.ZLabel1_3)
        self.DesiredFlightLayout.addLayout(self.FlightHLayout)
        self.FlightHLayout1 = QtWidgets.QHBoxLayout()
        self.FlightHLayout1.setObjectName("FlightHLayout1")
        self.XPositionUAV = QtWidgets.QLineEdit(self.verticalLayoutWidget_15)
        self.XPositionUAV.setText("")
        self.XPositionUAV.setObjectName("XPositionUAV")
        self.FlightHLayout1.addWidget(self.XPositionUAV)
        self.YPositionUAV = QtWidgets.QLineEdit(self.verticalLayoutWidget_15)
        self.YPositionUAV.setObjectName("YPositionUAV")
        self.FlightHLayout1.addWidget(self.YPositionUAV)
        self.ZPositionUAV = QtWidgets.QLineEdit(self.verticalLayoutWidget_15)
        self.ZPositionUAV.setObjectName("ZPositionUAV")
        self.FlightHLayout1.addWidget(self.ZPositionUAV)
        self.YAWUAV = QtWidgets.QLineEdit(self.verticalLayoutWidget_15)
        self.YAWUAV.setObjectName("YAWUAV")
        self.FlightHLayout1.addWidget(self.YAWUAV)
        self.DesiredFlightLayout.addLayout(self.FlightHLayout1)
        self.AutonomousTitle_2 = QtWidgets.QLabel(self.AutonomousFlightMode_Tab)
        self.AutonomousTitle_2.setGeometry(QtCore.QRect(640, 480, 671, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.AutonomousTitle_2.setFont(font)
        self.AutonomousTitle_2.setObjectName("AutonomousTitle_2")
        self.line = QtWidgets.QFrame(self.AutonomousFlightMode_Tab)
        self.line.setGeometry(QtCore.QRect(580, 540, 20, 251))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(630, 550, 280, 241))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.AutonomousTitle_4 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.AutonomousTitle_4.setFont(font)
        self.AutonomousTitle_4.setAlignment(QtCore.Qt.AlignCenter)
        self.AutonomousTitle_4.setObjectName("AutonomousTitle_4")
        self.gridLayout_4.addWidget(self.AutonomousTitle_4, 1, 1, 1, 3)
        self.tbDropHeight = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.tbDropHeight.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbDropHeight.sizePolicy().hasHeightForWidth())
        self.tbDropHeight.setSizePolicy(sizePolicy)
        self.tbDropHeight.setObjectName("tbDropHeight")
        self.gridLayout_4.addWidget(self.tbDropHeight, 6, 3, 1, 1)
        self.btnDropVelocity = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.btnDropVelocity.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDropVelocity.sizePolicy().hasHeightForWidth())
        self.btnDropVelocity.setSizePolicy(sizePolicy)
        self.btnDropVelocity.setObjectName("btnDropVelocity")
        self.gridLayout_4.addWidget(self.btnDropVelocity, 7, 1, 1, 2)
        self.tbDropVelocity = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.tbDropVelocity.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbDropVelocity.sizePolicy().hasHeightForWidth())
        self.tbDropVelocity.setSizePolicy(sizePolicy)
        self.tbDropVelocity.setObjectName("tbDropVelocity")
        self.gridLayout_4.addWidget(self.tbDropVelocity, 7, 3, 1, 1)
        self.btnSetHeight = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.btnSetHeight.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSetHeight.sizePolicy().hasHeightForWidth())
        self.btnSetHeight.setSizePolicy(sizePolicy)
        self.btnSetHeight.setObjectName("btnSetHeight")
        self.gridLayout_4.addWidget(self.btnSetHeight, 6, 1, 1, 2)
        self.tbTiltAngle = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.tbTiltAngle.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbTiltAngle.sizePolicy().hasHeightForWidth())
        self.tbTiltAngle.setSizePolicy(sizePolicy)
        self.tbTiltAngle.setObjectName("tbTiltAngle")
        self.gridLayout_4.addWidget(self.tbTiltAngle, 8, 3, 1, 1)
        self.btnTiltAngle = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.btnTiltAngle.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTiltAngle.sizePolicy().hasHeightForWidth())
        self.btnTiltAngle.setSizePolicy(sizePolicy)
        self.btnTiltAngle.setObjectName("btnTiltAngle")
        self.gridLayout_4.addWidget(self.btnTiltAngle, 8, 1, 1, 2)
        self.btnFreefall = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.btnFreefall.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFreefall.sizePolicy().hasHeightForWidth())
        self.btnFreefall.setSizePolicy(sizePolicy)
        self.btnFreefall.setObjectName("btnFreefall")
        self.gridLayout_4.addWidget(self.btnFreefall, 2, 1, 1, 2)
        self.btnRecovery = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.btnRecovery.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRecovery.sizePolicy().hasHeightForWidth())
        self.btnRecovery.setSizePolicy(sizePolicy)
        self.btnRecovery.setObjectName("btnRecovery")
        self.gridLayout_4.addWidget(self.btnRecovery, 2, 3, 1, 1)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(660, 350, 361, 111))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.IMULayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.IMULayout_2.setContentsMargins(0, 0, 0, 0)
        self.IMULayout_2.setObjectName("IMULayout_2")
        self.lblFailsafeController = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.lblFailsafeController.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lblFailsafeController.setObjectName("lblFailsafeController")
        self.IMULayout_2.addWidget(self.lblFailsafeController)
        self.IMUHLayout_2 = QtWidgets.QHBoxLayout()
        self.IMUHLayout_2.setObjectName("IMUHLayout_2")
        self.lblTiltPWM = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.lblTiltPWM.setObjectName("lblTiltPWM")
        self.IMUHLayout_2.addWidget(self.lblTiltPWM)
        self.lblThrottle = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.lblThrottle.setObjectName("lblThrottle")
        self.IMUHLayout_2.addWidget(self.lblThrottle)
        self.IMULayout_2.addLayout(self.IMUHLayout_2)
        self.IMU_DISP_2 = QtWidgets.QHBoxLayout()
        self.IMU_DISP_2.setObjectName("IMU_DISP_2")
        self.Tilt_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_7)
        self.Tilt_DISP.setObjectName("Tilt_DISP")
        self.IMU_DISP_2.addWidget(self.Tilt_DISP)
        self.throttle_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_7)
        self.throttle_DISP.setObjectName("throttle_DISP")
        self.IMU_DISP_2.addWidget(self.throttle_DISP)
        self.IMULayout_2.addLayout(self.IMU_DISP_2)
        WaterSamplingGroundControlStation.addTab(self.AutonomousFlightMode_Tab, "")
        self.References_Tab = QtWidgets.QWidget()
        self.References_Tab.setObjectName("References_Tab")
        self.ReferencesTitle = QtWidgets.QLabel(self.References_Tab)
        self.ReferencesTitle.setGeometry(QtCore.QRect(20, 20, 151, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ReferencesTitle.setFont(font)
        self.ReferencesTitle.setObjectName("ReferencesTitle")
        self.ReferencesInfo = QtWidgets.QLabel(self.References_Tab)
        self.ReferencesInfo.setGeometry(QtCore.QRect(30, 80, 491, 661))
        self.ReferencesInfo.setWordWrap(True)
        self.ReferencesInfo.setObjectName("ReferencesInfo")
        WaterSamplingGroundControlStation.addTab(self.References_Tab, "")

        self.retranslateUi(WaterSamplingGroundControlStation)
        WaterSamplingGroundControlStation.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(WaterSamplingGroundControlStation)

    def retranslateUi(self, WaterSamplingGroundControlStation):
        _translate = QtCore.QCoreApplication.translate
        WaterSamplingGroundControlStation.setWindowTitle(_translate("WaterSamplingGroundControlStation", "TabWidget"))
        self.InitTitle.setText(_translate("WaterSamplingGroundControlStation", "UAV INITIALIZATION"))
        self.Welcome.setText(_translate("WaterSamplingGroundControlStation", "<html><head/><body><p>Welcome to the Water Sampling Ground Control Station! Here you will be able to set up, monitor and fly the UAV autonomously or manually. To fly, please start ROSCore, MAVROS and OFFBOARD for communication and control with UAV</p></body></html>"))
        self.ROSCoreInfo.setText(_translate("WaterSamplingGroundControlStation", "<html><head/><body><p>ROS Core </p><p>Roscore is a collection of nodes and programs that make up the pre-requisites of the robot operating system. You must have one and only one roscore running to be able to do any communication between nodes, and therefore communicate and fly the UAV [1]</p></body></html>"))
        self.StartROSCore.setText(_translate("WaterSamplingGroundControlStation", "Start ROS Core"))
        self.MAVROSInfo.setText(_translate("WaterSamplingGroundControlStation", "<html><head/><body><p>MAVROS</p><p>MAVROS is a package that provides communication drivers for various autopilots with the MAVLink protocol. It additionally provides the UDP MAVLink bridge for ground control stations such as QGroundControl. We harness the same communication to generate this ground control station.<br/></p></body></html>"))
        self.StartMAVROS.setText(_translate("WaterSamplingGroundControlStation", "Start MAVROS Communication"))
        self.OFFBOARDInfo.setText(_translate("WaterSamplingGroundControlStation", "<html><head/><body><p>OFFBOARD</p><p>Offboard mode is a function supported by all Pixhawk flight controllers except the 3DR Pixhawk1 [3]. It allows the vehicle to obey position, velocity, accleeration, attitude, altitude rates or thrust setpoints provided by an external source to the flight stack such as a companion computer. In this case we use Jetson Nano to run the flight controller and communicate the data over the MAVLink protocal. [4]</p></body></html>"))
        self.StartOffboard.setText(_translate("WaterSamplingGroundControlStation", "Start OFFBOARD MODE"))
        WaterSamplingGroundControlStation.setTabText(WaterSamplingGroundControlStation.indexOf(self.Initialization_Tab), _translate("WaterSamplingGroundControlStation", "Initilization"))
        self.AutonomousTitle.setText(_translate("WaterSamplingGroundControlStation", "Autonomous Flight"))
        self.GPSLabel.setText(_translate("WaterSamplingGroundControlStation", "Global Position"))
        self.LatLabel.setText(_translate("WaterSamplingGroundControlStation", "Lateral"))
        self.LongLabel.setText(_translate("WaterSamplingGroundControlStation", "Longitudinal"))
        self.AltLabel.setText(_translate("WaterSamplingGroundControlStation", "Altitude (MSL)"))
        self.IMULabel.setText(_translate("WaterSamplingGroundControlStation", "IMU (Orientation °)"))
        self.XLabel0.setText(_translate("WaterSamplingGroundControlStation", "Roll"))
        self.YLabel0.setText(_translate("WaterSamplingGroundControlStation", "Pitch"))
        self.ZLabel0.setText(_translate("WaterSamplingGroundControlStation", "Yaw"))
        self.VelLabel.setText(_translate("WaterSamplingGroundControlStation", "Velocity"))
        self.U_VEL_Label.setText(_translate("WaterSamplingGroundControlStation", "U"))
        self.V_VEL_Label.setText(_translate("WaterSamplingGroundControlStation", "V"))
        self.W_VEL_Label.setText(_translate("WaterSamplingGroundControlStation", "W"))
        self.FlightTimeLabel.setText(_translate("WaterSamplingGroundControlStation", "Flight Time"))
        self.Min_Label.setText(_translate("WaterSamplingGroundControlStation", "Min"))
        self.Sec_Label.setText(_translate("WaterSamplingGroundControlStation", "Secs"))
        self.FlightLogTitle.setText(_translate("WaterSamplingGroundControlStation", "Flight Log"))
        self.EmergencyStop.setText(_translate("WaterSamplingGroundControlStation", "Emergency Stop\n"
"(Kills Motors)"))
        self.GPSLabel_2.setText(_translate("WaterSamplingGroundControlStation", "Relative Position"))
        self.LatLabel_2.setText(_translate("WaterSamplingGroundControlStation", "X"))
        self.LongLabel_2.setText(_translate("WaterSamplingGroundControlStation", "Y"))
        self.AltLabel_2.setText(_translate("WaterSamplingGroundControlStation", "Altitude (AGL)"))
        self.Voltage_Label.setText(_translate("WaterSamplingGroundControlStation", "Voltage:"))
        self.StateConnected.setText(_translate("WaterSamplingGroundControlStation", "DISCONNECTED"))
        self.StateARM.setText(_translate("WaterSamplingGroundControlStation", "DISARMED"))
        self.StateMode.setText(_translate("WaterSamplingGroundControlStation", "MODE"))
        self.StateVRS.setText(_translate("WaterSamplingGroundControlStation", "STATE"))
        self.DISARM.setText(_translate("WaterSamplingGroundControlStation", "Disarm"))
        self.Land.setText(_translate("WaterSamplingGroundControlStation", "Land"))
        self.ARM.setText(_translate("WaterSamplingGroundControlStation", "Arm"))
        self.HOLD.setText(_translate("WaterSamplingGroundControlStation", "STOP (Hold Mode)"))
        self.HOLD.setShortcut(_translate("WaterSamplingGroundControlStation", "Esc"))
        self.OFFBOARD.setText(_translate("WaterSamplingGroundControlStation", "OFFBOARD"))
        self.RESET_ORIGIN.setText(_translate("WaterSamplingGroundControlStation", "Reset EKF Origin"))
        self.AutonomousTitle_3.setText(_translate("WaterSamplingGroundControlStation", "MavROS State Machine"))
        self.SendPositionUAV.setText(_translate("WaterSamplingGroundControlStation", "Send New Position"))
        self.SendPositionUAV.setShortcut(_translate("WaterSamplingGroundControlStation", "Return"))
        self.GetCurrentPositionUAV.setText(_translate("WaterSamplingGroundControlStation", "Get Current Position"))
        self.DesiredFlightCoordinates.setText(_translate("WaterSamplingGroundControlStation", "Custom Flight Coordinates"))
        self.XLabel1.setText(_translate("WaterSamplingGroundControlStation", "X"))
        self.YLabel1.setText(_translate("WaterSamplingGroundControlStation", "Y"))
        self.ZLabel1.setText(_translate("WaterSamplingGroundControlStation", "Z"))
        self.ZLabel1_3.setText(_translate("WaterSamplingGroundControlStation", "Yaw"))
        self.AutonomousTitle_2.setText(_translate("WaterSamplingGroundControlStation", "Custom Application Controls"))
        self.AutonomousTitle_4.setText(_translate("WaterSamplingGroundControlStation", "Failsafe Testing State Machine"))
        self.tbDropHeight.setText(_translate("WaterSamplingGroundControlStation", "50"))
        self.btnDropVelocity.setText(_translate("WaterSamplingGroundControlStation", "Drop at Speed:"))
        self.tbDropVelocity.setText(_translate("WaterSamplingGroundControlStation", "1"))
        self.btnSetHeight.setText(_translate("WaterSamplingGroundControlStation", "Go to Drop Height:"))
        self.tbTiltAngle.setText(_translate("WaterSamplingGroundControlStation", "0"))
        self.btnTiltAngle.setText(_translate("WaterSamplingGroundControlStation", "Tilt Angle"))
        self.btnFreefall.setText(_translate("WaterSamplingGroundControlStation", "Freefall"))
        self.btnRecovery.setText(_translate("WaterSamplingGroundControlStation", "RECOVERY"))
        self.lblFailsafeController.setText(_translate("WaterSamplingGroundControlStation", "Failsafe Controller"))
        self.lblTiltPWM.setText(_translate("WaterSamplingGroundControlStation", "Tilt PWM"))
        self.lblThrottle.setText(_translate("WaterSamplingGroundControlStation", "Throttle"))
        WaterSamplingGroundControlStation.setTabText(WaterSamplingGroundControlStation.indexOf(self.AutonomousFlightMode_Tab), _translate("WaterSamplingGroundControlStation", "Autonomous Flight"))
        self.ReferencesTitle.setText(_translate("WaterSamplingGroundControlStation", "References"))
        self.ReferencesInfo.setText(_translate("WaterSamplingGroundControlStation", "<html><head/><body><p>[1] https://wiki.ros.org/roscore</p><p>[2] https://wiki.ros.org/mavros</p><p>[3] https://docs.px4.io/main/en/flight_controller/pixhawk.html</p><p>[4] https://docs.px4.io/main/en/flight_modes/offboard.html</p></body></html>"))
        WaterSamplingGroundControlStation.setTabText(WaterSamplingGroundControlStation.indexOf(self.References_Tab), _translate("WaterSamplingGroundControlStation", "References"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WaterSamplingGroundControlStation = QtWidgets.QTabWidget()
    ui = Ui_WaterSamplingGroundControlStation()
    ui.setupUi(WaterSamplingGroundControlStation)
    WaterSamplingGroundControlStation.show()
    sys.exit(app.exec_())
